### ISSUE TITLE
Contact summary extension

### ISSUE THREAD

**Issue by colemanw** [donchamil/uk.co.millertech.collapsecommsanddemographics#1]
Hey guys, just saw this cool extension and it's similar to the work I've been doing here: https://github.com/civicrm/org.civicrm.contactlayout

Allowing the admin to make blocks collapsible is on the roadmap for sure, which means the only feature left is your cool summary icons. Maybe we can collaborate to get those working together with the layout editor :)

**Comment by chamilwijesooriya** [comment]
@colemanw sorry I missed this didn't get any notifications.
layout editor looks awesome. We'd be happy to collaborate.

**Comment by chamilwijesooriya** [comment]
@colemanw it's now compatible with Contact Summary Layout Editor. just had to add hook_civicrm_contactSummaryBlocks

**Comment by colemanw** [comment]
Very nice. Glad you enjoyed playing with the Layout Editor :)

**Comment by chamilwijesooriya** [comment]
@colemanw layout editor is pretty cool
